---
- hosts: localhost
  remote_user: root

  tasks:
    - name: ensure open-vm-tools is installed
      yum: name=open-vm-tools state=latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      register: install

    - name: ensure open-vm-tools is installed
      apt: name=open-vm-tools state=latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      register: install


    - name: start open-vm-tools
      service: name=vmtoolsd enabled=yes state=reloaded
      when: install.changed == true
